### ISSUE TITLE
Wallpaper links?

### ISSUE THREAD

**Issue by gnussbaum67** [victor4pinheiro/dotfiles#1]
Not an issue per se, but do you have links to the wallpapers?

**Comment by victor4pinheiro** [comment]
[Gravity falls](https://www.reddit.com/r/wallpaper/comments/yyptpa/mystery_shack_3840x2160/)
[Second image](https://s1.1zoom.me/big0/596/Evening_Forests_Mountains_Firewatch_Campo_Santo_549147_1280x720.jpg)
